---
# tasks file for balancer

- name: installing haproxy loadbalancer
  package:
    name: "haproxy"
    state: present

- name: starting service 
  service:
    name: "haproxy"
    state: started

- name: copying config file
  template:
    src: "haproxy.j2"
    dest: "/etc/haproxy/haproxy.cfg"
  notify: changes

